Rx_home_work V_Sokolova
Otus-Android/HomeWork_06 pull request #108
Opened 2023-07-23 20:16 UTC by Sokolik411

2023-07-23 20:24 UTC, antonkazakov requested changes
Привет. Один коммент

2023-07-23 20:24 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +            .repeatWhen { it.delay(2000, TimeUnit.MILLISECONDS) }
А зачем тебе repeatWhen, у тебя же уже есть интервал

2023-07-23 20:29 UTC, Sokolik411 commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +            .repeatWhen { it.delay(2000, TimeUnit.MILLISECONDS) }
done. сначала по-другому сделала, забыла убрать

2023-08-06 09:34 UTC, antonkazakov commented
👍

2023-08-06 09:34 UTC, closed without merging