MikeKuzn's RXJava HW
Otus-Android/HomeWork_06 pull request #112
Opened 2023-08-20 16:37 UTC by MikeKuzn52

2023-08-31 11:09 UTC, antonkazakov requested changes
Привет. Оставил пару замечаний небольших

2023-08-31 11:09 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/MainActivity.kt
> +        catsViewModel.catsLiveData.removeObservers(this)
А зачем тебе управлять обсерверами так? Достаточно же просто в onClear отписаться

2023-08-31 11:09 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +            while (true) {
Давай попробуем это через операторы RXа сделать

2023-08-31 11:09 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +        _catsLiveData.postValue(Success(fact))
Можно везде где postValue перенести на Schedulers.Main и поменять на setvalue

2023-09-01 18:49 UTC, MikeKuzn52 commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +        _catsLiveData.postValue(Success(fact))
Да, конечно.  "//.observeOn(AndroidSchedulers.mainThread()) // postValue is **thread-safe**"
Поправил. 
postValue будет работать немного медленнее из-за synchronized, по этому предпочтительней писать AndroidSchedulers.mainThread(). Верно?

2023-09-17 09:17 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +        _catsLiveData.postValue(Success(fact))
Привет. Он и синхронизированный и еще есть один момент:

If you call postValue() and after that you call getValue(), you may not receive the value that you set in postValue(). If the main thread had already set the value, then you will get the value that you posted, but if the main thread hadn't set the value yet, then you don't get the value that you posted. So be careful if you work in background threads.

2023-09-17 09:17 UTC, closed without merging