Домашняя работа 3 (RxJava) Приходько
Otus-Android/HomeWork_06 pull request #128
Opened 2024-01-23 13:56 UTC by TECTRO

2024-01-31 17:37 UTC, antonkazakov requested changes
Привет! Оставил пару комментариев

2024-01-31 17:37 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/LocalCatFactsGenerator.kt
> +            .filter { facts ->
Я думаю тут можно чуть упростить  и заменить на один из distinct операторов

2024-01-31 17:37 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/LocalCatFactsGenerator.kt
> +    private val catFactsSubject = BehaviorSubject
А нужен ли здесь сабджект? Во вьюмодели в целом понятно, но тут кажется достаточно просто just/fromCallable?

2024-01-31 19:17 UTC, TECTRO commented on app/src/main/java/otus/homework/reactivecats/LocalCatFactsGenerator.kt
> +    private val catFactsSubject = BehaviorSubject
Хотя наверное да, по памяти не лучшее решение

2024-01-31 19:18 UTC, TECTRO commented on app/src/main/java/otus/homework/reactivecats/LocalCatFactsGenerator.kt
> +    private val catFactsSubject = BehaviorSubject
За то выигрыш в скорости :Р

2024-02-02 10:57 UTC, TECTRO commented on app/src/main/java/otus/homework/reactivecats/LocalCatFactsGenerator.kt
> +    private val catFactsSubject = BehaviorSubject
UPD. Упростил реализацию до простого lazy single

2024-02-02 10:57 UTC, TECTRO commented on app/src/main/java/otus/homework/reactivecats/LocalCatFactsGenerator.kt
> +            .filter { facts ->
заменил на distinctUntilCanged

2024-02-10 18:17 UTC, antonkazakov commented
👍

2024-02-10 18:17 UTC, closed without merging