Тимофеев
Otus-Android/HomeWork_06 pull request #130
Opened 2024-01-25 14:18 UTC by btimofeev

…го подключите Retrofit адаптер, поменяйте возвращаемые типы функций

2. Поменяйте логику в `CatsViewModel.kt` с колбеков на RX. Логику обработки успеха/ошибки из коллбека необходимо перенести в терминальные коллбеки RX цепочки. Не забудьте очистить подписки когда `ViewModel` уничтожается

3. Реализуйте функцию `otus.homework.reactivecats.LocalCatFactsGenerator#generateCatFact`, так, чтобы она возвращала `Fact` со случайной строкой  из массива строк `R.array.local_cat_facts` обернутую в подходящий стрим(`Flowable`/`Single`/`Observable` и т.п)

4. Реализуйте функцию `otus.homework.reactivecats.LocalCatFactsGenerator#generateCatFactPeriodically` так, чтобы она эмитила `Fact` со случайной строкой из массива строк `R.array.local_cat_facts` каждые 2000 миллисекунд. Если вновь заэмиченный Fact совпадает с предыдущим - пропускаем элемент.

5. Реализуйте функцию `otus.homework.reactivecats.CatsViewModel#getFacts` следующим образом:  каждые 2 секунды идем в сеть за новым фактом, если сетевой запрос завершился неуспешно, то в качестве фоллбека идем за фактом в уже реализованный `otus.homework.reactivecats.LocalCatFactsGenerator#generateCatFact`.

2024-01-31 17:53 UTC, antonkazakov requested changes
Привет. Оставил комментарии

2024-01-31 17:53 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +        disposable.add(
Чтобы уменьшить вложенность можно складывать в CompositeDisposable в коллбеке `doOnSubscribe`

2024-01-31 17:53 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +    val disposable = CompositeDisposable()
Ее нужно сделать приватной

2024-01-31 17:53 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                .map { response: Response<Fact> ->
С RxJava2CallAdapterFactory можно поменять возвращаемый тип на Fact, если будет неуспешный статус он сам смапится в исключение и полетит по цепочке

2024-02-01 13:54 UTC, btimofeev commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +        disposable.add(
исправил

2024-02-01 13:54 UTC, btimofeev commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +    val disposable = CompositeDisposable()
сделал приватной

2024-02-01 13:55 UTC, btimofeev commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                .map { response: Response<Fact> ->
убрал Response

2024-02-10 18:54 UTC, closed without merging