HomeWork_06
Otus-Android/HomeWork_06 pull request #154
Opened 2024-04-19 06:44 UTC by Sviridovamd

2024-04-28 10:24 UTC, antonkazakov requested changes
Привет. Оставил пару вопросов и замечаний

2024-04-28 10:24 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                .debounce(2000, TimeUnit.MILLISECONDS)
А зачем нам дебаунс здесь?

2024-04-28 10:24 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                    { error -> errorParser(error) })
Тут тоже хочется пользователю сообщить об ошибке, нужен эмит в лайвдату и какая-нибудь простая обработку

2024-04-28 10:24 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                .repeat()
А нужен ли тут repeate? в `generateCatFactPeriodically` интервал же итак периоически эмитит?

2024-05-02 11:24 UTC, Sviridovamd commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                .debounce(2000, TimeUnit.MILLISECONDS)
В задаче 5. Реализуйте функцию `otus.homework.reactivecats.CatsViewModel#getFacts` следующим образом:  каждые 2 секунды идем в сеть. Исправила на .repeatWhen { it.delay(2000, TimeUnit.MILLISECONDS) }

2024-05-02 11:24 UTC, Sviridovamd commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                    { error -> errorParser(error) })
Добавила { error -> _catsLiveData.postValue(errorParser(error)) })

2024-05-02 11:25 UTC, Sviridovamd commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                .repeat()
Убрала. Да, забыла что в generateCatFactPeriodically есть интервал

2024-05-05 09:03 UTC, antonkazakov requested changes
Еще один комментарий добавил

2024-05-05 09:03 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                    { error -> _catsLiveData.postValue(errorParser(error)) })
А ты же переключила выше на mainThread, зачем тогда postValue? Я думаю лучше везде поменять на setValue

2024-05-06 11:46 UTC, Sviridovamd commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                    { error -> _catsLiveData.postValue(errorParser(error)) })
Спасибо) Уяснила, что метод setValue уместен в основном потоке приложения, а postValue — если данные приходят из фонового потока.

2024-05-10 08:49 UTC, closed without merging