Aleksei Vinogradov - RX Java
Otus-Android/HomeWork_06 pull request #163
Opened 2024-07-15 10:38 UTC by aykme

2024-07-24 18:47 UTC, antonkazakov requested changes
Привет, оставил комментарии

2024-07-24 18:47 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +    fun getFacts(
А где подписка на этот обсервабл планируется? Она тут и должна быть, в качестве терминальных колбеков эмитить разные типа Result

2024-07-24 18:47 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                    .onErrorResumeNext(localCatFactsGenerator.generateCatFact())
А тут на каком шедулере будет?

2024-07-24 18:47 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +    ): Observable<Fact?> {
Разве может по цепочке null пролететь?

2024-07-25 15:53 UTC, aykme commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                    .onErrorResumeNext(localCatFactsGenerator.generateCatFact())
Тут на Main. Main устанавливается до doOnError, чтобы обновить LiveData через метод setServerErrorResult(). Иначе она не обновится корректно. onErrorResumeNext также в Main и generateCatFact(). Тут нет никакого смысла в дальнейшем переключении c Main на io, так как это локальная легкая операция. Больше ресурсов было бы потрачено на переключение шедулера.

2024-07-25 16:37 UTC, aykme commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +    ): Observable<Fact?> {
С сервера то все что угодно может прийти (в данном случае через метод sercive.getCatFact()). Например, может прийти пустое тело без ошибки.
Тут вопрос в том, какую логику мы ходим? Обрабатывать такой ответ или кидать в onError?
До перехода на RX через обработку retrofit.Call была закодирована возможность получения null. Я оставил такую же логику.
Проверка на null в данный момент находится перед установкой Success Result.
Чтобы вас это не смущало, убрал nullable у Fact. Теперь такие ответы будут попадать в onError

2024-07-25 16:41 UTC, aykme commented
Привет, ответил на комментарии

2024-07-28 08:57 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +    ): Observable<Fact?> {
Все что угодно придти с сервера не может. Есть строгий контракт который и клиент и сервер должны соблюдать.
Я написал комментарий потому что еще со 2 версии RxJava запретили эмитить нуллы в цепочке. Сразу эксепшен выпадет.
https://stackoverflow.com/questions/39781420/handling-null-in-rxjava2

2024-07-28 09:00 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +    fun getFacts(
Я, конечно, понимаю что метод уже был назван getFacts, но строить дизайн функции исходя из имени довольно странная затея.
В прослойке презентейшена VM/Presenter/Feature и прочих классах очень удобно менеджить подписки т.к. они довольно близко к ЖЦ находятся, а тут получается кто подписываться будет на него? Вью?

2024-07-28 09:00 UTC, closed without merging