ReactiveCats - HomeWork
Otus-Android/HomeWork_06 pull request #17
Opened 2021-10-18 12:36 UTC by flaming565

2021-10-31 15:01 UTC, antonkazakov requested changes
Привет. onError считаю нужно добавить обязательно

2021-10-31 15:01 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +    private val compositeDisposable = CompositeDisposable()
Думаю тут можно и одним Disposable обойтись, но в целом подход правильный

2021-11-01 09:21 UTC, flaming565 commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +    private val weakContext = WeakReference(context)
context потому что передается в аргументах, возможна утечка
да и сама студия ругается

2021-11-13 19:06 UTC, flaming565 commented
@antonkazakov исправила

2021-11-14 14:03 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +    private val weakContext = WeakReference(context)
Студия ругается превентивно. Она и `ApplicationContext` подсвечивает)
Я считаю, что тут вполне безопасно и обычную ссылку держать. У тебя контекст используется только в терминальном состоянии RX чейна, не думаю что где-то утечет.

2021-11-14 14:08 UTC, antonkazakov reviewed
Ответил про контекст и написал про эмиты нуллов. В целом, все ок и ПР закрываю

2021-11-14 14:08 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                    if (fact != null) _catsLiveData.value = Success(fact)
По цепочке начиная со 2 версии RXJava нельзя null гонять, так что если он будет null цепочка упадет https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#nulls

2021-11-14 14:08 UTC, closed without merging