HomeWork RxJava Tushov Alexander
Otus-Android/HomeWork_06 pull request #170
Opened 2024-08-06 19:04 UTC by Kachiro0121

2024-08-11 09:34 UTC, antonkazakov requested changes
привет. оставил два комментария

2024-08-11 09:34 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/LocalCatFactsGenerator.kt
> +            .distinctUntilChanged{ oldFact, newFact -> oldFact.text == newFact.text }
Я думаю можно тут деофлтную логику сравнения по equals обьектов использовать.
Тоесть заменить на distinctUntilChanged()

2024-08-11 09:34 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsService.kt
> +    fun getCatFact(): Single<Response<Fact>>
Можно убрать тип Response и всю логику связанную с его валидацией. Это уже все находится внутри РХКоллАдаптера

2024-08-13 20:02 UTC, Kachiro0121 commented
Удалил излишки кода.

2024-08-25 18:53 UTC, closed without merging