HomeWork_06: Виталий Чупин
Otus-Android/HomeWork_06 pull request #179
Opened 2024-10-13 12:58 UTC by vitalik123123

2024-10-21 06:34 UTC, antonkazakov requested changes
Привет. Оставил замечания

2024-10-21 06:34 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsService.kt
> +    fun getCatFact(): Observable<Response<Fact>>
1) Лучше поменять на Single т.к. эмит всегда один будет на этот запрос
2) Response лучше убрать т.к. адаптер сам смапит статусы != 2xx в исключение

2024-10-21 06:34 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +    val catsService: CatsService,
`private`

2024-10-21 06:34 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/LocalCatFactsGenerator.kt
> +            .retry()
А retry разве решит эту задачу? 
Во-первых насколько я помню он будет реэмитить только в случае ошибок
Во-вторых тут нет логики по фильтрации дубликатов

2024-10-21 06:34 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                .subscribe { response ->
А здесь и ниже как обработаются ошибки?

2024-10-23 15:07 UTC, vitalik123123 commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                .subscribe { response ->
сделал новый коммит с исправлением ошибок

2024-11-04 16:37 UTC, closed without merging