RxJava Homework
Otus-Android/HomeWork_06 pull request #32
Opened 2021-11-20 18:21 UTC by qdri1

2021-11-27 12:48 UTC, antonkazakov requested changes

2021-11-27 12:48 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsService.kt
> +    fun getCatFact(): Observable<Fact>
Думаю здесь Single лучше подойдет

2021-11-27 12:48 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                    localCatFactsGenerator.generateCatFact().blockingGet()
blockingGet() конечно лучше не использовать.
Возьми onErrorResumeNext, который возвращает один из рх стримов

2021-11-27 12:48 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +            catsService.getCatFact()
Я думаю можно одной цепочкой обойтись и не дублировать

2021-11-27 12:48 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +            localCatFactsGenerator.generateCatFactPeriodically()
А это зачем?

2021-11-27 12:48 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                .subscribe {
А где обработка ошибок?

2021-11-27 12:48 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                .subscribe {
Нет обработки onError

2021-11-27 12:48 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/LocalCatFactsGenerator.kt
> +        return Flowable
Тут нет оператора, которйы уберет дубликаты

2021-11-28 14:06 UTC, qdri1 commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +            localCatFactsGenerator.generateCatFactPeriodically()
убрал, просто тестировал функцию так как он больше нигде не вызывается

2021-12-05 15:27 UTC, antonkazakov reviewed
👍

2021-12-05 15:27 UTC, closed without merging