homework rxjava Ларин
Otus-Android/HomeWork_06 pull request #59
Opened 2022-08-04 12:26 UTC by fanrok

2022-08-13 20:19 UTC, antonkazakov requested changes

2022-08-13 20:19 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +    private val compositeDisposable by lazy {
Не думаю что тут есть смысл делать `lazy`, учитывая что ты в теле праймари конструктора уже к ней обращаешься)

2022-08-13 20:19 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                .subscribeBy(
А что делает subscribeBy?) Какой тут шедулер?

2022-08-13 20:19 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                        .blockingGet()
Считаю использование этой функции bad practice, она во первых блокирующая, во вторых никакого смысла здесь в ней нет

2022-08-13 20:19 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +        compositeDisposable.add(
У тебя дублируются цепочки тут и в getFacts, подумай что можно п ереиспользовать

2022-08-15 11:26 UTC, fanrok commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                .subscribeBy(
Библиотека RxKotlin, сахар для работы 
![image](https://user-images.githubusercontent.com/11526800/184627170-14b94935-f852-4c6c-a990-86fc599a85ee.png)

2022-08-15 11:27 UTC, fanrok commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                .subscribeBy(
шедулер для работы в ui не нужен тк я пользуюсь postValue у LiveData

2022-09-28 17:40 UTC, antonkazakov commented
👍

2022-09-28 17:40 UTC, closed without merging