Homework Reactive Cats from Pavel Scherbakov
Otus-Android/HomeWork_06 pull request #61
Opened 2022-08-15 08:27 UTC by PavelScherbakov

2022-08-28 20:14 UTC, antonkazakov requested changes
Привет. Оставил пару замечаний. Поправь, пожалуйста

2022-08-28 20:14 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsService.kt
> +    fun getCatFact(): Observable<Response<Fact>>
Мне кажется лучше здесь оставить Single<Fact>
Single правильнее с точки зрения стримов, у тебя же не будет здесь > 1 ивента
Response в твоей задаче не нужен, только придется дольше сидеть с распаковкой

2022-08-28 20:14 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/LocalCatFactsGenerator.kt
> +                } while (curIndex == preIndex)
Реализуй пожалуйста с использованием операторов)

2022-09-04 19:39 UTC, PavelScherbakov commented on app/src/main/java/otus/homework/reactivecats/CatsService.kt
> +    fun getCatFact(): Observable<Response<Fact>>
Исправил

2022-09-04 19:39 UTC, PavelScherbakov commented on app/src/main/java/otus/homework/reactivecats/LocalCatFactsGenerator.kt
> +                } while (curIndex == preIndex)
Сделал используя scan

2022-09-18 15:51 UTC, antonkazakov reviewed
Привет. Работу зачитываю, но посмоитри плз комментарий про distinct оператор,

2022-09-18 15:51 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/LocalCatFactsGenerator.kt
> +            .scan { pre, current ->
Вообще ты можешь взять оператор [distinctUntilChanged](https://reactivex.io/documentation/operators/distinct.html#collapseRxJava%C2%A01%E2%80%A4x)

2022-09-18 15:52 UTC, closed without merging