homework is done
Otus-Android/HomeWork_06 pull request #62
Opened 2022-08-15 08:51 UTC by sergey-i-am

2022-08-31 17:24 UTC, antonkazakov requested changes
Привет. Поправь, пожалуйста, замечания

2022-08-31 17:24 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/LocalCatFactsGenerator.kt
> +        return Flowable.interval(2000, TimeUnit.MILLISECONDS)
А где логика которая проверяет повтор это относительно предыдущего айтема или нет?

2022-08-31 17:24 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +            .subscribe()
А где обработка ошибок и успеха? 
Тебе нужно это сделать у результирующей цепочки а не дочерней

2022-09-02 12:30 UTC, sergey-i-am commented on app/src/main/java/otus/homework/reactivecats/LocalCatFactsGenerator.kt
> +        return Flowable.interval(2000, TimeUnit.MILLISECONDS)
добавил

2022-09-02 12:31 UTC, sergey-i-am commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +            .subscribe()
убрал вложенные цепочки

2022-09-11 07:50 UTC, antonkazakov requested changes

2022-09-11 07:50 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +            .subscribe { fact -> _catsLiveData.value = Success(fact) }
В целом даже если у тебя есть onErrorResumeNext, тебе нужно добавить обработку ошибок для всей цепочки, ведь у тебя и ниже может упасть исключение, например в `localCatFactsGenerator.generateCatFact()`

2022-09-12 10:04 UTC, sergey-i-am commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +            .subscribe { fact -> _catsLiveData.value = Success(fact) }
добавил обработку на всю цепочку, при эксепшне в localCatFactsGenerator.generateCatFact() отрабатывает

2022-09-28 17:37 UTC, antonkazakov commented
👍

2022-09-28 17:37 UTC, closed without merging