Sementsov Reactive cats HomeWork
Otus-Android/HomeWork_06 pull request #64
Opened 2022-08-22 06:42 UTC by DeveloperSementsov

Reactive cats HomeWork

2022-08-28 18:40 UTC, antonkazakov requested changes
Привет. Поправь, пожалуйста, замечания

2022-08-28 18:40 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/LocalCatFactsGenerator.kt
>      fun generateCatFactPeriodically(): Flowable<Fact> {
Попробуй реализовать задание используя операторы RX

2022-08-28 18:40 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                getFacts(context)
А зачем ты это делаешь в doAfterTerminate?

2022-08-28 18:40 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +        compositeDisposable.add(disposable)
Можно перенести в doOnSubscribe

2022-08-28 18:40 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                Single.fromCallable { catsService.getCatFact().execute() }
Ты же подключил CallAdapter, который конвертирует Call в RX стримы. используй его

2022-08-28 18:40 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +    private val _showProgressBar = MutableLiveData<Boolean>()
У тебя же есть уже Лайвдата которая эмитит Result, сделай еще один наследник, например, Loading, и не придется еще 2 лайвдаты добавлять

2022-08-28 18:40 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +            .observeOn(AndroidSchedulers.mainThread())
Ты же уже подписался выше

2022-08-28 18:40 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +            .subscribe()
А здесь не обрабатываются успех/ошибка?

2022-11-28 21:24 UTC, DeveloperSementsov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                Single.fromCallable { catsService.getCatFact().execute() }
done

2022-11-28 21:45 UTC, DeveloperSementsov commented on app/src/main/java/otus/homework/reactivecats/LocalCatFactsGenerator.kt
>      fun generateCatFactPeriodically(): Flowable<Fact> {
Flowable это оператор RX

2022-11-28 21:47 UTC, DeveloperSementsov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +        compositeDisposable.add(disposable)
Привычка :) Перенес

2022-11-28 22:15 UTC, DeveloperSementsov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                getFacts(context)
Переписал

2022-11-28 22:16 UTC, DeveloperSementsov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +    private val _showProgressBar = MutableLiveData<Boolean>()
Хорошая идея, сделал

2022-11-28 22:16 UTC, DeveloperSementsov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +            .observeOn(AndroidSchedulers.mainThread())
переписал

2022-11-28 22:20 UTC, DeveloperSementsov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +            .subscribe()
переписал

2022-12-11 14:57 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/LocalCatFactsGenerator.kt
>      fun generateCatFactPeriodically(): Flowable<Fact> {
Это не оператор РХ, это один из стримов. Есть операторы которые фильтруют дубликаты в цепочке

2022-12-12 19:06 UTC, DeveloperSementsov commented on app/src/main/java/otus/homework/reactivecats/LocalCatFactsGenerator.kt
>      fun generateCatFactPeriodically(): Flowable<Fact> {
добавил distinct()

2023-01-21 08:36 UTC, antonkazakov reviewed
👍

2023-01-21 08:36 UTC, closed without merging