ДЗ ReactiveCats
Otus-Android/HomeWork_06 pull request #66
Opened 2022-09-03 10:58 UTC by YolisStormbreaker

2022-09-11 18:55 UTC, antonkazakov requested changes
Привет. Оставил пару замечаний

2022-09-11 18:55 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +    private fun stopObserver() {
А чем не подошел `onCleared`?

2022-09-11 18:55 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/LocalCatFactsGenerator.kt
> +                .debounce(CAT_GENERATION_PERIOD_MILLISECONDS, TimeUnit.MILLISECONDS)
Интересное решение через тротлинг, но мне кажется через интервал лучше, сейчас с каким интервалом эмитятся евенты в генераторе?

2022-09-11 18:55 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/LocalCatFactsGenerator.kt
> +            Single.defer {
Мне кажется что здесь defer излишен, fromCallable будет достаточно

2022-09-11 18:55 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                .subscribe { fact ->
А где обработка ошибок? у тебя же в localCatFactsGenerator.generateCatFact() тоже может эксепшен выпасть

2022-09-11 18:55 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +        getFacts {  }
А зачем этот вызов?

2022-09-12 11:06 UTC, YolisStormbreaker commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +    private fun stopObserver() {
Забыл про него.

2022-09-12 11:13 UTC, YolisStormbreaker commented on app/src/main/java/otus/homework/reactivecats/LocalCatFactsGenerator.kt
> +                .debounce(CAT_GENERATION_PERIOD_MILLISECONDS, TimeUnit.MILLISECONDS)
Cейчас с интервалом CAT_GENERATION_PERIOD_MILLISECONDS == 2000 миллисекунд.
А разве у Flowable есть interval? Я нашёл только timeInterval, но он делает совсем иное.

2022-09-12 11:15 UTC, YolisStormbreaker commented on app/src/main/java/otus/homework/reactivecats/LocalCatFactsGenerator.kt
> +            Single.defer {
👍

2022-09-12 12:16 UTC, YolisStormbreaker commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                .subscribe { fact ->
👍

2022-09-12 12:27 UTC, YolisStormbreaker commented on app/src/main/java/otus/homework/reactivecats/LocalCatFactsGenerator.kt
> +                .debounce(CAT_GENERATION_PERIOD_MILLISECONDS, TimeUnit.MILLISECONDS)
Реализовал вариант с zipWith и interval.

2022-09-26 20:28 UTC, antonkazakov commented
👍

2022-09-26 20:28 UTC, closed without merging