Homework_6_by_Vb
Otus-Android/HomeWork_06 pull request #8
Opened 2021-08-26 04:33 UTC by VbiterGit

2021-09-08 20:24 UTC, antonkazakov requested changes

2021-09-08 20:24 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                .subscribe {
Тут не самое красивое решение получилось, попробуй взять `flatmap` также как ты сделал в `LocalCatFactsGenerator` и добавь `onErrorResumeNext`/`onErrorReturn`

2021-09-16 11:29 UTC, VbiterGit commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                .subscribe {
переделал с onErrorReturn

пробовал еще сделать c onErrorResumeNext вместо onErrorReturn и repeat(), почему-то interval перестает повторно запускать цепочку, не понял почему

2021-10-03 17:55 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                .subscribe {
Репит не нужен. По заданию нужно из кеша достать

2021-10-03 17:57 UTC, antonkazakov requested changes

2021-10-03 17:57 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                .subscribe {
Тебе вложенные сабскрайбы не нужны, не совсем RX way получается. Постарайся все в 1 цепочке сделать

2021-10-24 21:42 UTC, closed without merging