Homework_03_RxJava
Otus-Android/HomeWork_06 pull request #87
Opened 2023-02-02 15:41 UTC by Eugeniydak

2023-02-12 12:03 UTC, antonkazakov requested changes
Привет. Оставил замечания

2023-02-12 12:03 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                .subscribe {
Правильнее это вынести из терминального состояния цепочки. Используй операторы которые позволяют из одной цепочки получить другую

2023-02-12 12:03 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +        compositeDisposable.add(
А где здесь фоллбек на неудачный запрос?

2023-02-12 13:40 UTC, Eugeniydak commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +        compositeDisposable.add(
В onError делаем запрос localCatFactsGenerator.generateCatFact(). Или не про это речь?

2023-02-12 13:40 UTC, Eugeniydak commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +        compositeDisposable.add(
> А где здесь фоллбек на неудачный запрос?

В onError делаем запрос localCatFactsGenerator.generateCatFact(). Или не про это речь?

2023-02-16 14:49 UTC, Eugeniydak commented on app/src/main/java/otus/homework/reactivecats/CatsViewModel.kt
> +                .subscribe {
исправил

2023-02-19 10:32 UTC, antonkazakov commented
👍

2023-02-19 10:32 UTC, closed without merging