Pavel Iokhin
Otus-Android/HomeWork_06 pull request #88
Opened 2023-02-03 19:31 UTC by iohin

2023-02-12 12:06 UTC, antonkazakov requested changes
Привет. Оставил пару замечаний

2023-02-12 12:06 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/LocalCatFactsGenerator.kt
> +        return BehaviorSubject.generate<Fact?> {
Не понял зачем тебе тут Subject нужен. Subject нужен когда ты хочешь получить и обсервер и обсервабл.

Здесь достаточно какого-нибудь `fromCallable`

2023-02-12 12:06 UTC, antonkazakov commented on app/src/main/java/otus/homework/reactivecats/LocalCatFactsGenerator.kt
> +            Thread.sleep(2000)
Это нужно убрать, возьми операторы типа interval или delay

2023-02-13 11:06 UTC, iohin commented on app/src/main/java/otus/homework/reactivecats/LocalCatFactsGenerator.kt
> +        return BehaviorSubject.generate<Fact?> {
Тут наверное скорее исходил из того, чтобы попробовать использовать Subject

2023-02-19 15:18 UTC, closed without merging